<a href="https://colab.research.google.com/github/damiangohrh123/ml_projects/blob/main/classification/random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Random Forests on Titanic
"""
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load Titanic dataset from seaborn
titanic = sns.load_dataset("titanic")
titanic.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# Keep only the features we need
titanic = titanic[["survived", "pclass", "age", "sibsp", "parch", "fare", "sex", "embarked"]]

# Handle missing values
titanic["age"] = titanic["age"].fillna(titanic["age"].mean())
titanic["fare"] = titanic["fare"].fillna(titanic["fare"].mean())
titanic["embarked"] = titanic["embarked"].fillna(titanic["embarked"].mode()[0])

# One-hot encoding (convert categorical → dummy vars)
titanic = pd.get_dummies(titanic, columns=["sex", "embarked"], drop_first=True)
titanic.head(5)

,survived,pclass,age,sibsp,parch,fare,sex_male,embarked_Q,embarked_S
0,0,3,22.0,1,0,7.2500,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False
2,1,3,26.0,0,0,7.9250,False,False,True
3,1,1,35.0,1,0,53.1000,False,False,True
4,0,3,35.0,0,0,8.0500,True,False,True

In [ ]:
# Define features and target
feature_cols = ["pclass", "age", "sibsp", "parch", "fare",
                "sex_male", "embarked_Q", "embarked_S"]

X = titanic[feature_cols]
y = titanic["survived"]

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Random Forest. n_estimators = 100 -> Build 100 decision trees
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Evaluate
print("Accuracy:", accuracy_score(y_test, rf.predict(X_test)))
print("\nFeature Importances:")

# Loop over features, and their importance scores. Higher value = more important
for col, imp in zip(X.columns, rf.feature_importances_):
    print(f"{col}: {imp:.4f}")

Accuracy: 0.8044692737430168

Feature Importances:
pclass: 0.0821
age: 0.2552
sibsp: 0.0498
parch: 0.0375
fare: 0.2742
sex_male: 0.2670
embarked_Q: 0.0108
embarked_S: 0.0233